services:
  - type: web
    name: real-time-dashboard-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn dashboard.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: SPREADSHEET_ID
        value: 1L2rmaklLE-NFDdGNbQqkiHnJPCe08qguo2tEOX5oaNY
      - key: RANGE_NAME
        value: Sheet1!A:K 